language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

install:
    - dzil authordeps --missing | cpanm --no-skip-satisfied
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied

script:
    - dzil test --author --release
